services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../StatEduc_MINJEC:/var/www/html/
      - ../nginx/logs:/var/log/nginx/
  php:
    image: fpm-php-7-alpine
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-php.dockerfile
    expose:
      - 9000
    volumes:
      - ../StatEduc_MINJEC:/var/www/html/
      - ../php/php.ini:/usr/local/etc/php/php.ini
      - ../php/freetds.conf:/etc/freetds.conf
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - ../mssql/data:/var/opt/mssql/data
      - ../mssql/backup:/var/opt/mssql/backup
    hostname: mssqlhost 
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Root1234'
